version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vsts-variable-set/v1"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vsts-variable-set/v2"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vsts-variable-transform/v1"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vsts-variable-transform/v2"
    schedule:
      interval: "weekly"
